### ISSUE TITLE
地图转换工具

### ISSUE THREAD

**Issue by Pantyhose-X** [NaCln4c1/Boat_H2O-v4#3]
1、没有整合包
整合包你可以上传到 GitHub releases  " releases上传文件大小限制2GB"

2、我的世界地图转换成 [minetest](https://www.minetest.net) 
https://minetest.cosoc.cn/t/minecraft-minetest-windows-10/292

**Comment by chlorineAya** [comment]
1. 整合包我会通过新建网盘或者新开个仓库的方法来解决，目前正在完成全版本的制作
2. 没接触过Minetest，以后再说吧
